version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "deutsch-worterbuch"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6z4tfn5i0tk7"
s3_prefix = "deutsch-worterbuch"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
