AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  deutsch-worterbuch

  Sample SAM Template for deutsch-worterbuch

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  ListNounsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: list-nouns/built
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        ListNouns:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /nouns
            Method: get
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref NounsTable

  NounsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: WORTERBUCH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ListNounsApi:
    Description: "API Gateway endpoint URL for Prod stage for List Nouns function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ListNounsFunction:
    Description: "List Nouns Lambda Function ARN"
    Value: !GetAtt ListNounsFunction.Arn
  ListNounsFunctionIamRole:
    Description: "Implicit IAM Role created for List Nouns function"
    Value: !GetAtt ListNounsFunctionRole.Arn

  DynamoDBTable:
    Description: "Table created to store the data related to Deutsch Worterbuch API"
    Value: !Ref NounsTable
